export default ScreeNames = {
	SetUp: 'SetUp',
	SetUpSuccessScreen: 'SetUpSuccess',
	SetUpFailureScreen: 'SetUpFailure',
	TransactionScreen: 'Transaction',
	TransactionSuccessScreen: 'TransactionSuccess',
	TransactionFailureScreen: 'TransactionFailureScreen',
	InputCredentialsStep1: 'EnterKeyStoreFile',
	InputCredentialsStep2: 'EnterKeyStorePassword',
	InputCredentialsStep3: 'EnterPrivateKeyPassword',
	TransactionHistoryScreen: 'TransactionHistoryScreen',
	ProfileScreen: 'ProfileScreen',
	MainScreen: 'MainScreen',
	SubmitPageScreen: 'SubmitPage',
};
