/*
 * *© Copyright 2018 - 2020 Visa. All Rights Reserved.**
 *
 * NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.*
 *
 *  By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy (developer.visa.com/privacy).In addition, all permissible uses of the Software must be in support of Visa products, programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com). **THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL FAULTS” BASIS WITHOUT WARRANTY OR  CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.** All brand names are the property of their respective owners, used for identification purposes only, and do not imply product endorsement or affiliation with Visa. Any links to third party sites are for your information only and equally  do not constitute a Visa endorsement. Visa has no insight into and control over third party content and code and disclaims all liability for any such components, including continued availability and functionality. Benefits depend on implementation details and business factors and coding steps shown are exemplary only and do not reflect all necessary elements for the described capabilities. Capabilities and features are subject to Visa’s terms and conditions and may require development,implementation and resources by you based on your business and operational details. Please refer to the specific API documentation for details on the requirements, eligibility and geographic availability.*
 *
 * This Software includes programs, concepts and details under continuing development by Visa. Any Visa features,functionality, implementation, branding, and schedules may be amended, updated or canceled at Visa’s discretion.The timing of widespread availability of programs and functionality is also subject to a number of factors outside Visa’s control,including but not limited to deployment of necessary infrastructure by issuers, acquirers, merchants and mobile device manufacturers.*
 *
 */

/*
 * Funds Transfer API
 * The Funds Transfer API can pull funds from the sender&apos;s Visa account (in preparation for pushing funds to a recipient&apos;s account) in an Account Funding Transaction (AFT).  Additionally, the Funds Transfer API also provides functionality to push funds to the recipient&apos;s Visa account in an Original Credit Transaction (OCT).  If a transaction is declined, the Funds Transfer API can also return the funds to the sender&apos;s funding source in an Account Funding Transaction Reversal (AFTR). The API has been enhanced to allow originators to send their PushFundsTransactions(OCTs) and PullFundsTransactions(AFTs) to Visa for routing to multiple U.S. debit networks.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.funds_transfer_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Address
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2019-03-27T10:55:08.119+05:30[Asia/Kolkata]")
public class Address {


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("county")
    private String county = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("country")
    private String country = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("state")
    private String state = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("zipCode")
    private String zipCode = null;

    public Address county(String county) {
        this.county = county;
        return this;
    }


    /**
     * &lt;b&gt;Note:&lt;/b&gt;It contains 3-digit numeric FIPS county code of the money transfer operator/Originator.&lt;br&gt;&lt;br&gt;Required if cardAcceptor:address:country is \&quot;US\&quot;.
     *
     * @return county
     **/
    @ApiModelProperty(value = "<b>Note:</b>It contains 3-digit numeric FIPS county code of the money transfer operator/Originator.<br><br>Required if cardAcceptor:address:country is \"US\".")
    public String getCounty() {
        return county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    public Address country(String country) {
        this.country = country;
        return this;
    }


    /**
     * This field must contain the 3-character alpha country code for the country of the originator or money transfer operator.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#iso_country_and_currency_codes\&quot;&gt;ISO Codes&lt;/a&gt;
     *
     * @return country
     **/
    @ApiModelProperty(required = true, value = "This field must contain the 3-character alpha country code for the country of the originator or money transfer operator.<br><br>Refer to <a href=\"/request_response_codes#iso_country_and_currency_codes\">ISO Codes</a>")
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Address state(String state) {
        this.state = state;
        return this;
    }


    /**
     * &lt;b&gt;Note:&lt;/b&gt;State or province of the money transfer operator/Originator. &lt;br&gt;&lt;br&gt; Required if cardAcceptor:address:country is \&quot;US\&quot; or \&quot;CA\&quot;.
     *
     * @return state
     **/
    @ApiModelProperty(value = "<b>Note:</b>State or province of the money transfer operator/Originator. <br><br> Required if cardAcceptor:address:country is \"US\" or \"CA\".")
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Address zipCode(String zipCode) {
        this.zipCode = zipCode;
        return this;
    }


    /**
     * &lt;b&gt;Note:&lt;/b&gt;Zip/Postal code of the money transfer operator/Originator.&lt;br&gt;&lt;br&gt;Required if cardAcceptor:address:country is \&quot;US\&quot; or \&quot;CA\&quot;.
     *
     * @return zipCode
     **/
    @ApiModelProperty(value = "<b>Note:</b>Zip/Postal code of the money transfer operator/Originator.<br><br>Required if cardAcceptor:address:country is \"US\" or \"CA\".")
    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Address address = (Address) o;
        return Objects.equals(this.county, address.county) &&
                Objects.equals(this.country, address.country) &&
                Objects.equals(this.state, address.state) &&
                Objects.equals(this.zipCode, address.zipCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(county, country, state, zipCode);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Address {\n");

        sb.append("    county: ").append(toIndentedString(county)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}



