/*
 * *© Copyright 2018 - 2020 Visa. All Rights Reserved.**
 *
 * NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.*
 *
 *  By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy (developer.visa.com/privacy).In addition, all permissible uses of the Software must be in support of Visa products, programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com). **THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL FAULTS” BASIS WITHOUT WARRANTY OR  CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.** All brand names are the property of their respective owners, used for identification purposes only, and do not imply product endorsement or affiliation with Visa. Any links to third party sites are for your information only and equally  do not constitute a Visa endorsement. Visa has no insight into and control over third party content and code and disclaims all liability for any such components, including continued availability and functionality. Benefits depend on implementation details and business factors and coding steps shown are exemplary only and do not reflect all necessary elements for the described capabilities. Capabilities and features are subject to Visa’s terms and conditions and may require development,implementation and resources by you based on your business and operational details. Please refer to the specific API documentation for details on the requirements, eligibility and geographic availability.*
 *
 * This Software includes programs, concepts and details under continuing development by Visa. Any Visa features,functionality, implementation, branding, and schedules may be amended, updated or canceled at Visa’s discretion.The timing of widespread availability of programs and functionality is also subject to a number of factors outside Visa’s control,including but not limited to deployment of necessary infrastructure by issuers, acquirers, merchants and mobile device manufacturers.*
 *
 */

/*
 * Funds Transfer API
 * The Funds Transfer API can pull funds from the sender&apos;s Visa account (in preparation for pushing funds to a recipient&apos;s account) in an Account Funding Transaction (AFT).  Additionally, the Funds Transfer API also provides functionality to push funds to the recipient&apos;s Visa account in an Original Credit Transaction (OCT).  If a transaction is declined, the Funds Transfer API can also return the funds to the sender&apos;s funding source in an Account Funding Transaction Reversal (AFTR). The API has been enhanced to allow originators to send their PushFundsTransactions(OCTs) and PullFundsTransactions(AFTs) to Visa for routing to multiple U.S. debit networks.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.funds_transfer_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CardAcceptor
 */
public class CardAcceptor {


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("idCode")
    private String idCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("address")
    private Address address = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("name")
    private String name = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("terminalId")
    private String terminalId = null;

    public CardAcceptor idCode(String idCode) {
        this.idCode = idCode;
        return this;
    }


    /**
     * An identifier for the card acceptor (Visa Direct Originator). This value should be unique for each originator for whom you are sending transactions.
     *
     * @return idCode
     **/
    @ApiModelProperty(required = true, value = "An identifier for the card acceptor (Visa Direct Originator). This value should be unique for each originator for whom you are sending transactions.")
    public String getIdCode() {
        return idCode;
    }

    public void setIdCode(String idCode) {
        this.idCode = idCode;
    }

    public CardAcceptor address(Address address) {
        this.address = address;
        return this;
    }


    /**
     * Get address
     *
     * @return address
     **/
    @ApiModelProperty(required = true, value = "")
    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public CardAcceptor name(String name) {
        this.name = name;
        return this;
    }


    /**
     * name of the originator/money transfer operator.
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "name of the originator/money transfer operator.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CardAcceptor terminalId(String terminalId) {
        this.terminalId = terminalId;
        return this;
    }


    /**
     * The identifier for the terminal at a card acceptor location. If sending transactions from a card not present environment, use the same value for all transactions.
     *
     * @return terminalId
     **/
    @ApiModelProperty(required = true, value = "The identifier for the terminal at a card acceptor location. If sending transactions from a card not present environment, use the same value for all transactions.")
    public String getTerminalId() {
        return terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CardAcceptor cardAcceptor = (CardAcceptor) o;
        return Objects.equals(this.idCode, cardAcceptor.idCode) &&
                Objects.equals(this.address, cardAcceptor.address) &&
                Objects.equals(this.name, cardAcceptor.name) &&
                Objects.equals(this.terminalId, cardAcceptor.terminalId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idCode, address, name, terminalId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CardAcceptor {\n");

        sb.append("    idCode: ").append(toIndentedString(idCode)).append("\n");
        sb.append("    address: ").append(toIndentedString(address)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    terminalId: ").append(toIndentedString(terminalId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}



