export default ScreeNames = {
	SetUp: 'SetUp',
	SetUpSuccessScreen: 'SetUpSuccess',
	SetUpFailureScreen: 'SetUpFailure',
	TransactionScreen: 'Transaction',
	TransactionSuccessScreen: 'TransactionSuccess',
	TransactionFailureScreen: 'TransactionFailureScreen',
	InputCredentialsStep1: 'EnterKeyStoreFile',
	InputCredentialsStep2: 'EnterKeyStorePassword',
	InputCredentialsStep3: 'EnterPrivateKeyPassword',
	HomeScreen: 'HomeScreen',
	ProfileScreen: 'ProfileScreen',
	MainScreen: 'MainScreen',
	// InputCredentialsStep4: 'EnterKey',
	// InputCredentialsStep5: 'EnterClientCertificate',
	SubmitPageScreen: 'SubmitPage',
};
